### ISSUE TITLE
Create `routes` type

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy-router#14]
This function needs to match the `react-router` equivalent.

See https://github.com/idom-team/idom-router/issues/2 for more details.

**Comment by rmorshea** [comment]
This is referred to as a router presently. Can rename though.

**Comment by Archmonger** [comment]
`routes` and `route` are two different callables in `react-router`.

As far as I can tell, the only difference is `routes` can match multiple routes at once, while `route` will only use the first match.

**Comment by Archmonger** [comment]
Closing due to this admonition on the react router docs

> If you're using a data router like [createBrowserRouter](https://reactrouter.com/en/main/routers/create-browser-router) it is uncommon to use this component as routes defined as part of a descendant <Routes> tree cannot leverage the [Data APIs](https://reactrouter.com/en/main/routers/picking-a-router#data-apis) available to [RouterProvider](https://reactrouter.com/en/main/routers/router-provider) apps.
