### ISSUE TITLE
Handle Server-side History Changes

### ISSUE THREAD

**Issue by rmorshea** [reactive-python/reactpy-router#19]
Right now, there is not way to trigger changes in history that will modify the client-side history as well. This is [not presently feasible](https://github.com/reactive-python/reactpy/issues/975) without changes to ReactPy core since there is no way for server-side components to send messages to client-side components - only client-side components can send messages to server-side ones.

**Comment by Archmonger** [comment]
What do you mean by history? VDOM transformation history? Or browser URL history?

**Comment by rmorshea** [comment]
Ok, my initial statement that this is not feasible isn't true. React Router uses a `<Navigate>` component that, if displayed, will change the browsers current URL. This could easily be implemented.

**Comment by Archmonger** [comment]
Closed in favor of #26
