### ISSUE TITLE
Links only work with string arguments

### ISSUE THREAD

**Issue by stevej2608** [reactive-python/reactpy-router#27]
The following works:
```
link('Users', to='/users')
```
When I replace 'Users' with a html composite, eg:

```
button = html.button({'class_name': '...'},
            icon(),
            html.span({'class_name': ...'}, 'Users')
        )

link(button, to='/users')
```

The button composite is rendered as an empty `<div></div>`. The button composite renders correctly outside the link.

**Comment by stevej2608** [comment]
I've done a quick hack [here](https://github.com/stevej2608/reactpy-router) that goes some way to fixing the problem. I can now create links that include an SVG icon and a *html.span()* containing the link text.

I'm pretty sure it will choke on links that contain nested *@component* definitions.

**Comment by Archmonger** [comment]
This is a more broad issue related to client-side components.

Right now, rendering server side components as a children of client-side components is really buggy.

**Comment by Archmonger** [comment]
For traceability, here's [another related issue](https://discord.com/channels/1111078259854168116/1205180183741730846) with the link component.

I will check if the link component can be rewritten as a server-side component in the next `reactpy_router` version.
